#!/usr/bin/env bash

mkBackup() {
  local shellName
  local ts
  shellName="$(basename "$SHELL")"
  ts="$(date +%Y-%m-%d_%H-%M-%S)"

  case "$shellName" in
    fish)
      [[ -f "$HOME/.config/fish/config.fish" ]] || return 1
      cp "$HOME/.config/fish/config.fish" \
         "$HOME/.config/fish/config.fish.bashgit.bak.$ts"
      ;;

    bash)
      [[ -f "$HOME/.bashrc" ]] || return 1
      cp "$HOME/.bashrc" \
         "$HOME/.bashrc.bashgit.bak.$ts"
      ;;

    zsh)
      [[ -f "$HOME/.zshrc" ]] || return 1
      cp "$HOME/.zshrc" \
         "$HOME/.zshrc.bashgit.bak.$ts"
      ;;

    *)
      echo "Unsupported shell: $shellName" >&2
      return 1
      ;;
  esac

  echo "Backup created successfully for $shellName"
}

checkPath() {
    if [[ "$PATH" = *"$HOME/bashgit/scripts"* ]]; then
        return 0
    else
        return 1
    fi
}


mkExe() {

local path="$HOME/bashgit/scripts/*"

    for file in "$path"; do
        if [[ -f "$file" &&  ! -x "$file" ]]; then # -x checks the if "$file" exists and have execute permission
            chmod +x "$file"
            echo "Made $file executable"
        fi
    done

}



addToPath() {
    local shellName=$(basename "$SHELL")

    if checkPath; then
        echo "Path already contains $HOME/bashgit/scripts"
        return 0
    fi

    case "$shellName" in
        fish)
            echo "fish_add_path $HOME/bashgit/scripts" >> "$HOME/.config/fish/config.fish"
            ;;
        zsh)
            echo "export PATH=\"$HOME/bashgit/scripts:\$PATH\"" >> "$HOME/.zshrc"
            ;;
        bash)
            echo "export PATH=\"$HOME/bashgit/scripts:\$PATH\"" >> "$HOME/.bashrc"
            ;;
        *)
            echo "Unknown shell: $shellName" >&2
            return 1
            ;;
    esac

    echo "Added to PATH. Restart your terminal or source your config."
}




mkBackup
mkExe
addToPath
