#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")/../lib/git_library"

checkPaths(){
    #checking if path exist in shell config
    echo "$PATH" | grep -q "$HOME/bashgit/scripts" && return 0 || return 1 
}

checkDir(){
    local dir
    dir="$HOME/bashgit"

    if [[ -d "$dir" ]]; then
        return 0
    else
        return 1
    fi
}

rmPaths(){
    local Dir
    local path
    local shellName
    shellName="$(basename "$SHELL")"
    Dir="$HOME/bashgit/scripts"

    case "$shellName" in 
        fish)
        fish -c "set -U fish_user_paths (string match -v '*bashgit*' \$fish_user_paths)" 
        ;;
        bash)
        sed -i '' '/bashgit\/scripts/d' "$HOME/.bashrc"
        ;;
        zsh)
        sed -i '' '/bashgit\/scripts/d' "$HOME/.zshrc"
        ;;
        *)
        echo "Unsupported shell: $shellName" >&2
        return 1
        ;;
    esac
}

rmDir(){
    local Dir
    Dir="$HOME/bashgit"
    if checkDir; then
        rm -r "$Dir" || return 1
        echo "Deleted the bashgit"
    else
        echo "Directory $Dir not found." >&2
        return 1
    fi
}

if promptYN "Uninstall bashgit?"; then
    rmPaths || echo "Failed to remove paths" >&2
    rmDir || echo "Failed to delete directory" >&2
    echo "bashgit removed successfully."
else
    echo "Uninstall cancelled."
fi