#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")/../lib/git_library"

#checking if path exist in shell config
checkPaths(){

    echo "$PATH" | grep -q "$HOME/bashgit/scripts" && return 0 || return 1 

}

#checking if bashgit directory exist
checkDir(){

    local dir
    dir="$HOME/bashgit"

    if [[ -d "$dir" ]]; then
        return 0
    else
        return 1
    fi
}
#removing bashgit directory
rmDir(){
    local Dir
    Dir="$HOME/bashgit"
    if checkDir; then
        rm -r "$Dir" || return 1
        echo "Deleted the bashgit"
    else
        echo "Directory $Dir not found." >&2
        return 1
    fi
}

# Main uninstallation logic
if promptYN "Uninstall bashgit?"; then
    rmPaths || echo "Failed to remove paths" >&2
    rmDir || echo "Failed to delete directory" >&2
    echo "bashgit removed successfully."
else
    echo "Uninstall cancelled."
fi